[package]
name = "omenic-web-state"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
daemon = { path = "../../infra/daemon" }
session = { path = "../../infra/session" }
memory = { path = "../../infra/memory" }
tools = { path = "../../agent/tools" }
adaptor = { path = "../../agent/adaptor" }
orbit = { path = "../../agent/orbit" }
