[package]
name = "web-state"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
agent-loop = { path = "../agent-loop" }
serde = { workspace = true }
serde_json = { workspace = true }
session = { path = "../session" }
memory = { path = "../memory" }
tools = { path = "../tools" }
llm = { path = "../llm" }
store = { path = "../store" }
