[package]
name = "omenic-web-page-workspace"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
omenic-web-client = { path = "../client" }
omenic-web-components = { path = "../components" }
omenic-web-state = { path = "../state" }
omenic-web-mock = { path = "../mock" }
omenic-web-page-stats = { path = "../page-stats" }
omenic-web-page-config = { path = "../page-config" }
dioxus = { version = "0.7" }
