[package]
name = "web-page-workspace"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
web-client = { path = "../web-client" }
web-components = { path = "../web-components" }
web-state = { path = "../web-state" }
web-page-stats = { path = "../web-page-stats" }
web-page-config = { path = "../web-page-config" }
dioxus = { version = "0.7" }
tokio = { version = "1", default-features = false, features = ["sync"] }
serde_json = { workspace = true }
