[package]
name = "omenic-web-client"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ureq = { workspace = true }
toml = { workspace = true }
pulldown-cmark = { workspace = true }
dioxus = { version = "0.7" }
dioxus_components = "0.1.2"
config = { path = "../../infra/config" }
adaptor = { path = "../../agent/adaptor" }
orbit = { path = "../../agent/orbit" }
tools = { path = "../../agent/tools" }
memory = { path = "../../infra/memory" }
session = { path = "../../infra/session" }
task = { path = "../../agent/task" }
